# Generated by Django 4.1.2 on 2022-10-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers_user_level_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="level",
        ),
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
