# Generated by Django 4.1.2 on 2022-10-08 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=10)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('meaning', models.CharField(max_length=100)),
                ('onyomi', models.TextField(blank=True, null=True)),
                ('kunyomi', models.TextField(blank=True, null=True)),
                ('image', models.URLField()),
                ('strokes', models.TextField()),
                ('video', models.URLField()),
            ],
            options={
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='kanji.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterExamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.CharField(max_length=1000)),
                ('meaning', models.CharField(max_length=1000)),
                ('audio', models.URLField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char', to='kanji.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ManyToManyField(related_name='characters', through='kanji.FlashCard', to=settings.AUTH_USER_MODEL),
        ),
    ]
