# Generated by Django 4.1.2 on 2022-10-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='grades',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
