# Generated by Django 4.1.2 on 2022-10-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0002_character_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='grades',
        ),
        migrations.AlterField(
            model_name='character',
            name='grade',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
