# Generated by Django 4.1.2 on 2022-10-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0003_remove_character_grades_alter_character_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='grades',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
