# Generated by Django 4.1.2 on 2022-10-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0004_character_grades_alter_character_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['grades']},
        ),
        migrations.RemoveField(
            model_name='character',
            name='grade',
        ),
    ]
